feat: added Rene's Mastodon
fharper/coffeechat pull request #37
Opened 2023-01-24 14:41 UTC by Topener

I added my mastodon account. For some reason, a lot of other lines also suddenly changed, which might be due to my formatter, I believe it's a newline issue with mixed newlines (windows vs. mac)

2023-01-24 16:23 UTC, fharper requested changes
Please update your information by modifying `people.json`, not `README.md` which is autogenerated. Instructions are in the README for more details.

2023-01-25 08:40 UTC, Topener commented
@fharper I completely blanked here, thanks! I changed the PR and updated the script to support Mastodon, and fixed a trailing comma issue for socials.

2024-04-18 14:35 UTC, fharper approved these changes

2024-04-18 14:36 UTC, merged

2024-04-18 14:37 UTC, fharper commented
Thanks for adding Mastodon, and fixing the rendering issue.